### ISSUE TITLE
Sum Question Update Requires JSON file Upload

### ISSUE THREAD

**Issue by Elvictor01** [statistical-perceptions/survey-builder#38]
When adding some questions, if you configure the question and try to update the experiment at a later time you are met with the box to drop a JSON file instead of showing the last saved experiment view.

P.S. The experiment formerly configured is stored

**Comment by brownsarahm** [comment]
@awqmayo can you look at this ?

**Comment by awqmayo** [comment]
@Elvictor01 Do you know if this is just for the sum question or is it for other questions as well?

**Comment by brownsarahm** [comment]
this is the same as #44
